tunnel: YOUR-TUNNEL-ID

originRequest:
  http2Origin: true
  noTLSVerify: false

loglevel: info

metrics: localhost:2000

ingress:
  - hostname: mc.fufu.land
    service: tcp://0.0.0.0:25565

  - hostname: ssh.fufu.land
    service: ssh://localhost:24212
  
  # Route subdomain to local service
  # - hostname: app.example.com
  #   service: http://localhost:3000
  
  # Route path to different service  
  # - hostname: example.com
  #   path: /api/*
  #   service: http://localhost:8080
  
  # SSH over cloudflared
  # - hostname: ssh.example.com
  #   service: ssh://localhost:22
  
  # Catch-all rule (required)
  - service: http_status:404