# A vibrant rainbow theme!

format = """
[ 道 ](fg:#E84855)\
[](#E84855)\
$os\
$username\
[](bg:#F9A03F fg:#E84855)\
$directory\
[](bg:#F3DE2C fg:#F9A03F)\
$git_branch\
$git_status\
[](bg:#7AC74F fg:#F3DE2C)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](bg:#2D82B7 fg:#7AC74F)\
$docker_context\
[](bg:#9C59D1 fg:#2D82B7)\
$time[](bg:#9C59D1 fg:#FFFFFF)\
[ ](fg:#9C59D1)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

[username]
show_always = true
style_user = "bg:#E84855 fg:#FFFFFF"
style_root = "bg:#E84855 fg:#FFFFFF"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#E84855 fg:#FFFFFF"
disabled = true # Disabled by default

[directory]
style = "bg:#F9A03F fg:#2C2C2C"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "径 "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
style = "bg:#7AC74F fg:#FFFFFF"
format = '[ ($version) ]($style)'

[cpp]
style = "bg:#7AC74F fg:#FFFFFF"
format = '[ ($version) ]($style)'

[docker_context]
style = "bg:#2D82B7 fg:#FFFFFF"
format = '[ $context ]($style)'

[elixir]
style = "bg:#7AC74F fg:#FFFFFF"
format = '[ ($version) ]($style)'

[elm]
style = "bg:#7AC74F fg:#FFFFFF"
format = '[ ($version) ]($style)'

[git_branch]
symbol = "支"
style = "bg:#F3DE2C fg:#2C2C2C"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#F3DE2C fg:#2C2C2C"
format = '[$all_status$ahead_behind ]($style)'

[golang]
style = "bg:#7AC74F fg:#FFFFFF"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#7AC74F fg:#FFFFFF"
format = '[ $symbol ($version) ]($style)'

[haskell]
style = "bg:#7AC74F fg:#FFFFFF"
format = '[ $symbol ($version) ]($style)'

[java]
style = "bg:#7AC74F fg:#FFFFFF"
format = '[ $symbol ($version) ]($style)'

[julia]
style = "bg:#7AC74F fg:#FFFFFF"
format = '[ $symbol ($version) ]($style)'

[nodejs]
format = '[ ($version) ](bg:#7AC74F fg:#FFFFFF)'

[nim]
style = "bg:#7AC74F fg:#FFFFFF"
format = '[ ($version) ]($style)'

[rust]  
style = "bg:#7AC74F fg:#FFFFFF"
format = '[ ($version) ]($style)'

[scala]
style = "bg:#7AC74F fg:#FFFFFF"
format = '[ ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#9C59D1 fg:#FFFFFF"
format = '[ 爱 $time ]($style)'
